### ISSUE TITLE
Unable to connect to 192.168.254.117:8443: IO::Socket::IP configuration failed at QVD/Client/Proxy.pm line 364 thread 1.

### ISSUE THREAD

**Issue by joeymorenoischoolsystemsnet** [theqvd/theqvd#66] opened 2017-07-12 04:10 UTC
Hi Everyone,

I hope you guys are doing fine.

I would like to ask some help from you regarding my connection issue.
My QVD Server is Ubuntu Server 17.04 and my QVD Client is Windows 7 Professional.

I followed the QVD Installation Guide on your website and come up with the following data:

----------------------------------------------------------------------
**Node.conf**

```
#
# QVD Node Configuration
#

# Name of this node in QVD. Usually the machine's hostname.
nodename=qvdnode

# Database connection information.
# database.host: where the QVD database is found
# database.name: the name of the QVD database
# database.user: the user account needed to connect
# database.password: the password needed to connect
database.host =localhost
database.name =qvddb
database.user =qvd
database.password =passw0rd

path.run = /var/run/qvd
path.log = /var/log/qvd
path.tmp = /var/tmp/qvd

log.filename = /var/log/qvd/qvd.log

wat.admin.login=admin
wat.admin.password=admin

log.level=ERROR
```

--------------------------------------------------------------------------
**/etc/network/interfaces**

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eno1
iface eno1 inet dhcp
# This is an autoconfigured IPv6 interface
iface eno1 inet6 auto

auto qvdnet0
iface qvdnet0 inet static
  pre-up brctl addbr qvdnet0
  pre-up iptables -t nat -A POSTROUTING -o eth0 -j SNAT --to-source 192.168.254.117
  pre-up iptables -t nat -A PREROUTING -d 192.168.254.117 -p tcp --dport 8443 -j DNAT --to-destination 10.3.15.1
  post-down brctl delbr qvdnet0
  address 10.3.15.1
  netmask 255.255.255.0

```
------------------------------------------------------------------------------------
**Network bridge**

```
# qa4 config set tenant_id=-1,key=vm.network.ip.start,value=10.3.15.50
# qa4 config set tenant_id=-1,key=vm.network.netmask,value=24
# qa4 config set tenant_id=-1,key=vm.network.gateway,value=10.3.15.1
# qa4 config set tenant_id=-1,key=vm.network.dns_server,value=10.3.15.254
# qa4 config set tenant_id=-1,key=vm.network.bridge,value=qvdnet0

```
-------------------------------------------------------------------------------------

I have also created the following on my WAT:
Users: 1
Virtual machines: 1
Nodes: 1
OS Flavours: 1
Disk Images: 1

![screenshot from 2017-07-12 11-44-36](https://user-images.githubusercontent.com/30099839/28101026-a5d57f90-667a-11e7-96a0-258e96196edc.png)

But i am very confused why my node is in stopped state
![screenshot from 2017-07-12 11-53-33](https://user-images.githubusercontent.com/30099839/28101118-4435e274-667b-11e7-8e77-207838b6a2bb.png)

And when i tried to run my node i always got this error
![screenshot from 2017-07-12 11-53-49](https://user-images.githubusercontent.com/30099839/28101167-7bf02990-667b-11e7-8b74-dc359479e0ef.png)

So I think Node is one of the reasons why my client can't connect to my server.

By the way, I am using separate CPUs for my Server and Client and i used Cisco Hub and CAT 5 for my connection.

Client IP Address:
![capture](https://user-images.githubusercontent.com/30099839/28101305-9699ec80-667c-11e7-8237-70fef8c5d37b.JPG)

Server IP Address:
![screenshot from 2017-07-12 11-44-08](https://user-images.githubusercontent.com/30099839/28101317-aa20792c-667c-11e7-8de1-f0b7f16ba451.png)

Lastly, here's the client QVD UI Information
![capture1](https://user-images.githubusercontent.com/30099839/28101431-4b7c4c24-667d-11e7-9367-0ea4cb33a863.JPG)
![capture3](https://user-images.githubusercontent.com/30099839/28101435-5147c58e-667d-11e7-8f34-5851b789012e.JPG)

I hope you could help me with this.

THANK YOU IN ADVANCE!

**Comment by Romulo123** [comment] 2017-07-12 05:11
lolo mo

**Comment by salva** [comment] 2017-07-12 06:29
Hi,

The web administration tool says all the nodes are down.

You should start the HKD server and check that it keeps running. Look into `/var/log/qvd.log` for errors on the server machine.

**Comment by salva** [comment] 2017-07-12 06:39
Also,

> `# qa4 config set tenant_id=-1,key=vm.network.dns_server,value=10.3.15.254`

The IPs above `vm.network.ip.start` (in your case, 10.3.15.50) are reserved for the virtual machines. You can not use them for your own purposes.

**Comment by joeymorenoischoolsystemsnet** [comment] 2017-07-13 02:23
Hi Salva,

Good day.

Thank you for your response.

Can you help me how to make it possible to run my node?
Well, I already started my HKD Server using this codes "service qvd-hkd start" but my node is still cannot be able to run.

What i'm trying to do is to connect the QVD Server and QVD Client using my computer(windows 7) and my server(ubuntu server 17.02) via ethernet cable CAT5 and Cisco Switch. Kindly see the image below:
![image](https://user-images.githubusercontent.com/30099839/28147695-2a8f4240-6737-11e7-8438-6a31ef823f0c.png)


Client IP(windows 7): 192.168.254.111
Server IP(Ubuntu Server 17.04): 192.168.254.117

QVD Client>> Settings>> Server(textbox): 192.168.254.117

Please let me know what's wrong to my set up.

Thank you soooo much!

**Comment by salva** [comment] 2017-07-13 07:51
Hi

You need to look into `/var/log/qvd.log` for errors.

**Comment by joeymorenoischoolsystemsnet** [comment] 2017-07-13 07:58
Hi

Below is the details for qvd.log:

-----------------qvd.log--------------------
2017/07/13 10:24:05 7287 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 365 - Host IP address is outside of the network range reserved for hosts (IP: 192.168.254.117, range: 10.3.15.0-10.3.15.50)
2017/07/13 12:58:14 9896 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 365 - Host IP address is outside of the network range reserved for hosts (IP: 192.168.254.117, range: 10.3.15.0-10.3.15.50)

Please let me know if you need more details or resources. Thanks!

**Comment by salva** [comment] 2017-07-13 08:00
You have incorrectly configured the node in the database. You should register it using the IP in the QVD internal network (10.3.15.0/24), the one for qvdnet0.

**Comment by joeymorenoischoolsystemsnet** [comment] 2017-07-13 08:45
Below are my configured data-file in my server.
Please help me identify the errors and please provide the correct configuration for my errors.
I really don't have an idea what will I do to correct the errors.

_________________________
**/etc/qvd/node.conf** 

#
# QVD Node Configuration
#

# Name of this node in QVD. Usually the machine's hostname.
nodename=qvdnode

# Database connection information.
# database.host: where the QVD database is found
# database.name: the name of the QVD database
# database.user: the user account needed to connect
# database.password: the password needed to connect
database.host = localhost
database.name = qvddb
database.user = qvd
database.password = passw0rd

path.run = /var/run/qvd
path.log = /var/log/qvd
path.tmp = /var/tmp/qvd

log.filename = /var/log/qvd/qvd.log

wat.admin.login=admin
wat.admin.password=admin

log.level=ERROR
----------------------------------



**/etc/qvd/api.conf**

database.host=localhost
database.name=qvddb
database.user=qvd
database.password=passw0rd
api.user=www-data
api.group=www-data
path.api.ssl=/etc/qvd/certs
--------------------------------------------------------------------------



**/etc/network/interfaces**

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eno1
iface eno1 inet dhcp
# This is an autoconfigured IPv6 interface
iface eno1 inet6 auto

auto qvdnet0
iface qvdnet0 inet static
  pre-up brctl addbr qvdnet0
  pre-up iptables -t nat -A POSTROUTING -o eth0 -j SNAT --to-source 192.168.254.117
  pre-up iptables -t nat -A PREROUTING -d 192.168.254.117 -p tcp --dport 8443 -j DNAT --to-destination 10.3.15.1
  post-down brctl delbr qvdnet0
  address 10.3.15.1
  netmask 255.255.255.0
-------------------------------------------



**/etc/postgresql/9.6/main/pg_hba.conf**

host qvddb qvd 192.168.254.117/24 md5

# PostgreSQL Client Authentication Configuration File
# ===================================================
#
# Refer to the "Client Authentication" section in the PostgreSQL
# documentation for a complete description of this file.  A short
# synopsis follows.
#
# This file controls: which hosts are allowed to connect, how clients
# are authenticated, which PostgreSQL user names they can use, which
# databases they can access.  Records take one of these forms:
#
# local      DATABASE  USER  METHOD  [OPTIONS]
# host       DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostssl    DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostnossl  DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
#
# (The uppercase items must be replaced by actual values.)
#
# The first field is the connection type: "local" is a Unix-domain
# socket, "host" is either a plain or SSL-encrypted TCP/IP socket,
# "hostssl" is an SSL-encrypted TCP/IP socket, and "hostnossl" is a
# plain TCP/IP socket.
#
# DATABASE can be "all", "sameuser", "samerole", "replication", a
# database name, or a comma-separated list thereof. The "all"
# keyword does not match "replication". Access to replication
# must be enabled in a separate record (see example below).
#
# USER can be "all", a user name, a group name prefixed with "+", or a
# comma-separated list thereof.  In both the DATABASE and USER fields
# you can also write a file name prefixed with "@" to include names
# from a separate file.
#
# ADDRESS specifies the set of hosts the record matches.  It can be a
# host name, or it is made up of an IP address and a CIDR mask that is
# an integer (between 0 and 32 (IPv4) or 128 (IPv6) inclusive) that
# specifies the number of significant bits in the mask.  A host name
# that starts with a dot (.) matches a suffix of the actual host name.
# Alternatively, you can write an IP address and netmask in separate
# columns to specify the set of hosts.  Instead of a CIDR-address, you
# can write "samehost" to match any of the server's own IP addresses,
# or "samenet" to match any address in any subnet that the server is
# directly connected to.
#
# METHOD can be "trust", "reject", "md5", "password", "gss", "sspi",
# "ident", "peer", "pam", "ldap", "radius" or "cert".  Note that
# "password" sends passwords in clear text; "md5" is preferred since
# it sends encrypted passwords.
#
# OPTIONS are a set of options for the authentication in the format
# NAME=VALUE.  The available options depend on the different
# authentication methods -- refer to the "Client Authentication"
# section in the documentation for a list of which options are
# available for which authentication methods.
#
# Database and user names containing spaces, commas, quotes and other
# special characters must be quoted.  Quoting one of the keywords
# "all", "sameuser", "samerole" or "replication" makes the name lose
# its special character, and just match a database or username with
# that name.
#
# This file is read on server startup and when the postmaster receives
# a SIGHUP signal.  If you edit the file on a running system, you have
# to SIGHUP the postmaster for the changes to take effect.  You can
# use "pg_ctl reload" to do that.

# Put your actual configuration here
# ----------------------------------
#
# If you want to allow non-local connections, you need to add more
# "host" records.  In that case you will also need to make PostgreSQL
# listen on a non-local interface via the listen_addresses
# configuration parameter, or via the -i or -h command line switches.

# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
-----------------------------------------------



/etc/postgresql/9.6/main/postgresql.conf

listen_addresses = '*'
default_transaction_isolation = 'serializable'


THANK YOU SO MUCH!

**Comment by salva** [comment] 2017-07-13 09:06
I am going to close this issue as a duplicate of #65. Please follow the conversation there.

**Closed by salva** 2017-07-13 09:06 UTC
